### PR TITLE
Mcstas instrument parser and data loader.

### LINKED ISSUE #10: Geometric information parsing (McStas loader mainly)
NMX data loader should be able to retrieve...

- detector rotation (x, y, z)
- detector position
- relative (x, y, z) list (?)
- source position
- sample position
- fast vector list
- slow vector list

In the McStas simulation file, there is a h5 group ``instrument/instrument_xml/`` that contains geometry information of the instruments.
McStas loader should be able to parse the xml information to retrieve the information above.

TODO:
 - [ ] Compare instrument view with mantid

### PR DESCRIPTION
**Pull request by YooSunYoung**
Fixes #10 
Data loader now load geometry coordinates as well by parsing instrument geometry xml in the McStas file.\

TODO:
- [x] Write algebra tests.
- [ ] Write position checking tests.

### CODE REVIEW

**Comment by YooSunYoung** [comment]
image

@Justin-Bergmann 
This is how it looks like when I plot the instrument view with subset of data.
Does it look right...?
And I need you to help me after holidays with some questions : D 
Until then, happy Christmas and happy new year...!

**Comment by Justin-Bergmann** [comment]
Unfortunately it does not look right, it should look like a box with only three sides. We can next year look together at it

**Comment by YooSunYoung** [comment]
image


How about the source position and sample position...?

**Comment by YooSunYoung** [comment]
Closing this in favor of #18

**Pull request closed without merging**
