### PR TITLE
Documentation update about overall process of data reduction and use latest sciline html wrapper.

### LINKED ISSUE #22: Document whole data reduction steps.
NMX data is partially reduced with scipp and the rest of the steps are done by external software.
Still we would like to have all the information in one place.

Here are some information that IDS(Justin) provided:
- https://dials.github.io/ (https://github.com/toastisme/dials)
- https://github.com/mlund/pyscale
- https://www.ccp4.ac.uk/
- https://www.ccp4.ac.uk/html/aimless.html
- https://www.ccp4.ac.uk/html/ctruncate.html

Also received slides about these steps through the slack channel : D

TODO
- [ ] Use pipeline html wrapper of sciline(>24.1.1) instead of parsing the function signature...!

### LINKED ISSUE #40: Use ``Pipeline._repr_html_`` after dropping python3.9
Once we drop python3.9, we can use `Pipeline._repr_html_`
Currently it's broken since it is not showing the real name of the ``NewType`` in python3.9

### PR DESCRIPTION
**Pull request by YooSunYoung**
Fixes #22
Fixes #40

### CODE REVIEW

**Comment by YooSunYoung** [comment]
I wanted to use ``mermaid`` instead of png file, but the docs build didn't work as expected...
I'm not sure why...

Here is the mermaid graph I wrote:

```mermaid
stateDiagram
    direction TB
    Step0: StartingExperiment
    Step1: Setting up Measurement Strategy
    Step0 --> Step1
    state ECDC {
        Step2: Data Readout from Detectors
    }
    Step1 --> ECDC
    state SCIPP {
        Step3.0: TOA to TOF
    }
    ECDC --> SCIPP
    state DIALS {
        direction LR
        Step3.1: 1. Spot Finding
        Step3.2: 2. TOF to &lambda
        Step3.3: 3. Indexing
        Step3.4: 4. Refine Indexing
        Step3.5: 5. Spot Integration
        Step3.1 --> Step3.2
        Step3.2 --> Step3.3
        Step3.3 --> Step3.4
        Step3.4 --> Step3.5
    }
    SCIPP --> DIALS
    state pyscale: pyscale {
        Step3.6: Scaling (temporarily using LSCALE)
    }
    DIALS --> pyscale
    state CCP4 {
        direction LR
        Step3.7: Merging, AIMLESS
        Step3.8: I to SFs
        Step3.7 --> Step3.8
    }
    pyscale --> CCP4
    state PHENIX {
        direction LR
        Step4.0: Phasing
        Step4.0 --> Step4.1
        state MODELCOMPLETED {
            state refine <<choice>>
            state map <<choice>>
            Step4.1: Model Completion
            Step4.2: Refinement
            Step4.3: MapCalculation
            Step4.4: Done
            Step4.1 --> Step4.2
            Step4.2 --> refine
            refine --> Step4.4
            refine --> Step4.3
            Step4.3 --> map
            map --> Step4.4
            map --> Step4.1
        }
    }
    CCP4 --> PHENIX
    Step5: Finished Experiment
    PHENIX --> Step5
```

**Comment by SimonHeybrock** [comment]
Mermaid should work acording to https://github.com/mgaitan/sphinxcontrib-mermaid?tab=readme-ov-file#markdown-support.

**Comment by YooSunYoung** [comment]
> Mermaid should work according to https://github.com/mgaitan/sphinxcontrib-mermaid?tab=readme-ov-file#markdown-support.

Yeah... but whenever I build the docs, it keeps showing up as a raw text or a raw code-snippet...
Is there any other projects using mermaid in the docs?

**Comment by YooSunYoung** [comment]
@Justin-Bergmann just approved after reviewing with me in person ...! Can anyone @scipp/ess-maintainers review this please..?  :D Then I'll release it...!

**Comment by YooSunYoung** [comment]
And Justin said he'll send the latex code for the diagram.
I'll update them later once I have it.

**Review by jokasimr — APPROVED** [review]

**Pull request merged**
